import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@/lib/Providers";
import Navbar from "@/components/view/Navbar";
import FooterComponent from "@/components/view/Footer";
import PublicHeader from "@/components/ui/PublicHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Highway Hoppers",
  description: "Generated by Imran Hossain",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <FooterComponent />
        </Providers>
      </body>
    </html>
  );
}
